apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: abrnoc-platform
  namespace: argocd
spec:
  description: AbrNOC platform GitOps project
  sourceRepos:
    - https://github.com/sadeqrm/AbrNOC-TASK.git
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
