---
all:
  children:

    control_plane:
      hosts:

        k8s-cp-01:
          ansible_host: 10.10.10.11

        k8s-cp-02:
          ansible_host: 10.10.10.12

        k8s-cp-03:
          ansible_host: 10.10.10.13

    workers:
      hosts:

        k8s-worker-01:
          ansible_host: 10.10.10.21

        k8s-worker-02:
          ansible_host: 10.10.10.22
