---
- name: Deploy Keepalived configuration
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: "0600"
  notify:
    - Restart keepalived


- name: Ensure Keepalived is enabled and running
  ansible.builtin.service:
    name: keepalived
    state: started
    enabled: true
