---
kubernetes_version: "v1.36.3"

kubernetes_api_domain: "api.k8s.lab"
kubernetes_api_vip: "10.10.10.100"
kubernetes_api_port: 8443
kubernetes_api_backend_port: 6443

kubernetes_control_plane_endpoint: >-
  {{ kubernetes_api_domain }}:{{ kubernetes_api_port }}

kubernetes_pod_subnet: "10.244.0.0/16"
kubernetes_service_subnet: "10.96.0.0/12"

containerd_socket: "unix:///run/containerd/containerd.sock"

kubeadm_config_dir: "/etc/kubernetes"
kubeadm_config_file: "/etc/kubernetes/kubeadm-init.yaml"
