---
containerd_package_name: containerd

containerd_config_dir: /etc/containerd

containerd_config_file: /etc/containerd/config.toml

containerd_service_name: containerd

containerd_cri_socket: unix:///run/containerd/containerd.sock
