---
- name: Deploy kubeadm init configuration
  ansible.builtin.template:
    src: kubeadm-init.yaml.j2
    dest: "{{ kubeadm_config_file }}"
    owner: root
    group: root
    mode: "0600"

- name: Validate kubeadm configuration
  ansible.builtin.command:
    cmd: "kubeadm config validate --config {{ kubeadm_config_file }}"
  changed_when: false

- name: Initialize first Kubernetes control-plane node
  ansible.builtin.command:
    cmd: "kubeadm init --config {{ kubeadm_config_file }} --upload-certs"
  args:
    creates: /etc/kubernetes/admin.conf
  register: kubeadm_init

- name: Show kubeadm init output
  ansible.builtin.debug:
    var: kubeadm_init.stdout_lines
  when: kubeadm_init is changed
